FROM maven:3-jdk-11-openj9

RUN mkdir -p /usr/src/app
VOLUME [ "/usr/src/app" ]
WORKDIR /usr/src/app
EXPOSE 8088

COPY . .
COPY docker/config.properties src/main/resources/config.properties

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y --no-install-recommends nodejs

RUN npm install && mvn clean compile

CMD mvn spring-boot:run